name="GPGPreferences"
appName="GPGPreferences.prefPane"

rmName="Uninstall.app"
imgBackground="Installer/background_dmg.png";
volumeLayout="Installer/DS_Store"



unset REVISION PRERELEASE
#PRERELEASE=b8

MAJOR=1
REVISION=2

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
