name="GPGPreferences"
appName="GPGPreferences.prefPane"

rmName="Uninstall.app"
imgBackground="Installer/background_dmg.png";
volumeLayout="Installer/DS_Store"

sshKeyname="Sparkle GPGPreferences - Private key" # TODO: Create this key!


unset REVISION PRERELEASE
MAJOR=0
MINOR=9
REVISION=2
#PRERELEASE=b8

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
